name: Build Steps

on:
    push:
        branches: [ main ]
    workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    - name: Update config.json version
        uses: jossef/action-set-json-field@v2
        with:
            file: config.json
            field: env.urlsetting
            value: HelloThere