name: Build Steps

on:
    push:
        branches: [ main ]
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Run a one-line script
          run: echo Hello, Sean
        #- name: Checkout code
        - uses: actions/checkout@v2
        - name: Update config.json version
          uses: jossef/action-set-json-field@v2
          with:
            file: config.json
            field: local.urlsetting
            value: HelloThere
        - name: Zip artifact for deployment
          run: zip release.zip * -r -x *.git*
        - name: Archive production artifacts
          uses: actions/upload-artifact@v3
          with:
            name: node-app
            path: release.zip
