name: Build Steps

on:
    push:
        branches: [ main ]
    workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
    - uses: actions/checkout@v2
    # - name: Update config.json version
    # - uses: jossef/action-set-json-field@v2
    # - with:
    #     file: config.json
    #     field: env.urlsetting
    #     value: HelloThere
